{% set name = "las-geoh5" %}
{% set version = "0.2.2" %}
{% set python_min = "3.10" %}
{% set python_max = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 1c20e6bb021516ef89de8551dc1f47f944bc98ea83d3da393d13e71469add43d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - geoh5_to_las = las_geoh5.scripts.geoh5_to_las:main
    - las_to_geoh5 = las_geoh5.scripts.las_to_geoh5:main

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }},<{{ python_max }}
    - geoh5py >=0.9.0,<0.10.0
    - lasio >=0.31
    - numpy >=1.23.5,<1.24.0
    - pydantic >=2.5.2,<2.6.0
    - tqdm >=4.66.1,<4.67.0

test:
  imports:
    - las_geoh5
  commands:
    - pip list
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Import/Export LAS files to/from geoh5 format.'
  description: |
    Import/Export LAS files to/from geoh5 format.

    This package allows for import and export of LAS files to and from a drillhole group. There is a module each for import and export operations. Each of these includes a driver and a ui.json that parameterizes the driver and renders a UI for use within Geoscience ANALYST Pro. Read on to learn how to install las-geoh5 and get started importing and exporting LAS files.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://mirageoscience-las-geoh5.readthedocs-hosted.com/en/stable/
  dev_url: https://github.com/MiraGeoscience/las-geoh5

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
