schema_version: 1

context:
  name: las-geoh5
  version: 0.2.2
  python_min: 3.10
  python_max: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 1c20e6bb021516ef89de8551dc1f47f944bc98ea83d3da393d13e71469add43d

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - geoh5_to_las = las_geoh5.scripts.geoh5_to_las:main
      - las_to_geoh5 = las_geoh5.scripts.las_to_geoh5:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.0.0
    - setuptools
    - setuptools_scm
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - geoh5py >=0.9.0,<0.10.0
    - lasio >=0.31
    - numpy >=1.23.5,<1.24.0
    - pydantic >=2.5.2,<2.6.0
    - tqdm >=4.66.1,<4.67.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - las_geoh5
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip list

about:
  summary: Import/Export LAS files to/from geoh5 format.
  description: |
    Import/Export LAS files to/from geoh5 format.

    This package allows for import and export of LAS files to and from a drillhole group.
    There is a module each for import and export operations. Each of these includes a driver and a ui.json 
    that parameterizes the driver and renders a UI for use within Geoscience ANALYST Pro.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/las-geoh5
  documentation: https://mirageoscience-las-geoh5.readthedocs-hosted.com/en/stable/

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
