schema_version: 1

context:
  name: las-geoh5
  version: "0.3.2"
  python_min: '3.10'
  module_name: ${{ name|lower|replace("-", "_") }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: b417ccfe9c025ce0ac9590753204c86192948bef27852c81a0087bb02e151771

build:
  number: 0
  noarch: python
  script:
    - export POETRY_DYNAMIC_VERSIONING_BYPASS=${{ version }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - geoh5_to_las = las_geoh5.scripts.geoh5_to_las:main
      - las_to_geoh5 = las_geoh5.scripts.las_to_geoh5:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, 1.*
    - setuptools
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoh5py 0.12.*
    # direct dependencies
    - lasio 0.31.*
    - numpy 1.26.*
    - pydantic >=2.5.2, 2.*
    - tqdm >=4.66.1, 4.*

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - ${{ module_name }}
        - ${{ module_name }}._version
        # dependency imports
        - geoh5py
        - lasio
      pip_check: true
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/
  - package_contents:
      files:
        - site-packages/${{ module_name }}/_version.py

about:
  summary: Import/Export LAS files to/from geoh5 format.
  description: |
    Import/Export LAS files to/from geoh5 format.

    This package allows for import and export of LAS files to and from a drillhole group.
    There is a module each for import and export operations. Each of these includes a driver and a ui.json 
    that parameterizes the driver and renders a UI for use within Geoscience ANALYST Pro.
  license: MIT
  license_file:
    - LICENSE
    - docs/source/THIRD_PARTY_SOFTWARE.rst
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/las-geoh5
  documentation: https://mirageoscience-las-geoh5.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
