schema_version: 1

context:
  name: las-geoh5
  version: 0.3.0
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: c5a8d61db1d4c1ad665fe434f132a377bb6ae47cf87d41dfde6d8eb9fd4055d4

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - geoh5_to_las = las_geoh5.scripts.geoh5_to_las:main
      - las_to_geoh5 = las_geoh5.scripts.las_to_geoh5:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.0.0
    - setuptools
    - setuptools_scm
  run:
    - python >=${{ python_min }}
    - geoh5py >=0.10.0,<0.11.dev
    - lasio >=0.31
    - numpy >=1.26.0,<1.27.dev
    - pydantic >=2.5.2,<2.6.dev
    - tqdm >=4.66.1,<4.67.dev

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - las_geoh5
      pip_check: true
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/

about:
  summary: Import/Export LAS files to/from geoh5 format.
  description: |
    Import/Export LAS files to/from geoh5 format.

    This package allows for import and export of LAS files to and from a drillhole group.
    There is a module each for import and export operations. Each of these includes a driver and a ui.json 
    that parameterizes the driver and renders a UI for use within Geoscience ANALYST Pro.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/las-geoh5
  documentation: https://mirageoscience-las-geoh5.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - sebhmg
    - conda-forge/geoh5py
